name: Publish to gh-pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: GabrielCappelli/gh-pages-pelican-action@0.1.5
        env:
          PELICAN_CONTENT_FOLDER: ./docs/content/
          PELICAN_CONFIG_FILE : ./docs/pelicanconf.py
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
